# Generated by Django 3.2.13 on 2022-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='movies', to='movies.Genre'),
        ),
    ]
