# Generated by Django 3.2.13 on 2022-11-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(default=0, related_name='movies', to='movies.Genre'),
        ),
    ]
